### ISSUE TITLE
Improve docker-compose for using latest template #1

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-zabbix#1]

**Comment by zengxc-1996** [comment]
Access via web page:
![image](https://user-images.githubusercontent.com/63622990/117756912-a1b4ae00-b251-11eb-92ab-1fca49aa75c1.png)

Query authority:
![image](https://user-images.githubusercontent.com/63622990/117756941-a8dbbc00-b251-11eb-9b98-2a77e66a9dc9.png)

**Comment by zengxc-1996** [comment]
## docker logs zabbix-proxy:
![image](https://user-images.githubusercontent.com/63622990/117802942-a34d9880-b288-11eb-8231-f0c06298afb7.png)

**Comment by qiaofeng1227** [comment]
Done
